# general settings
name: experient_param_0
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_SuperRestoration_param
    denoise_rate: true
    # dataroot_sr: /mnt/mnt/data1/YTH/Image_Sonar_Generate/flsea-vi/red_sea/sub_pier/SonarParams2/suResSonar
    # dataroot_gt: /mnt/mnt/data1/YTH/Image_Sonar_Generate/flsea-vi/red_sea/sub_pier/SonarParams2/clearSonar
    # dataroot_lq: /mnt/mnt/data1/YTH/Image_Sonar_Generate/flsea-vi/red_sea/sub_pier/SonarParams2/noiseSonar

    dataroot_sr: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarDenoiseRate/suResSonar
    dataroot_gt: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarDenoiseRate/clearSonar
    dataroot_lq: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarDenoiseRate/noiseSonar
    dataroot_param: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarDenoiseRate/params
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    drop_last: True
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [6,6,2,1,1,1]             # Batch size per gpu   
    iters: [3000,2000,1600,1200,1200,800]
    gt_size: 128   # Max patch size for progressive training
    gt_sizes: [32,64,96,128,128,128]  # Patch sizes for progressive training.
    prob: 0
    # probs: [0.2,0.2,0.3,0.2,0.1,0.1]
    probs: [0.2,0.1,0.05,0.03,0.02,0.02]

    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    # mini_batch_sizes: [8]   
    # iters: [300000]
    # gt_size: 128   
    # gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_SuperRestoration_param
    denoise_rate: true
    dataroot_sr: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarParams/suResSonar
    dataroot_gt: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarParams/clearSonar
    dataroot_lq: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarParams/noiseSonar
    dataroot_param: /mnt/mnt/data2/YTH/Image_Sonar_Generate/flsea-vi/canyons/flatiron/SonarParams/params
    io_backend:
      type: disk

# network structures
network_g:
  type: RestormerSuperResolutionParam2
  inp_channels: 3  
  out_channels: 3
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: BiasFree
  dual_pixel_task: False
  static: 'no'
  params: 'cat'  # 'cat', 'plus', or 'mul' for different parameter handling
  
# path
path:
  pretrain_network_g: ~ #/mnt/mnt/data2/YTH/Restomer/Denoising/pretrained_models/gaussian_color_denoising_blind.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  total_iter: 50000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [100000, 8000]  
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]    
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 1e-5
    weight_decay: !!float 0.5e-4
    betas: [0.2, 0.999]
  
  # losses
  pixel_opt:
    type: L1LossSr
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 300e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
