# general settings
name: dev_MultiFrameDenoiserStudentLite_4_prob04
model_type: ImageCleanModel 
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedMutiImage
    # dataroot_gt: /mnt/data1/YTH/Datasets/Image_Sonar_Generate/flsea-vi/red_sea/sub_pier/Sonar2/clearSonar
    # dataroot_lq: /mnt/data1/YTH/Datasets/Image_Sonar_Generate/flsea-vi/red_sea/sub_pier/Sonar2/noiseSonar
    # dataroot_gt: '/mnt/mnt/data2/YTH/FLSData/MDWdenoise/denoise/restormer_params'  # `高质量图像文件夹路径`
    dataroot_gt: '/mnt/mnt/data2/YTH/FLSData/MDWdenoise/sorted/denoise/RestormerSuperResolutionParam2'  # `高质量图像文件夹路径`
    dataroot_lq: '/mnt/mnt/data2/YTH/FLSData/MDWdenoise/sorted/noise1/origin'  # 低   geometric_augs: true
    geometric_augs: true
    num_pairs: 7
    stride_range: [1,1]
  
    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [128,128,64,32,32,32]            # Batch size per gpu   
    iters: [30000,20000,16000,12000,12000,10000]        
    # iters: [60000,40000,32000,24000,24000,16000]
    # iters: [92000,64000,48000,36000,36000,24000,50000]
    gt_size: 384   # Max patch size for progressive training
    gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
    prob: 0
    probs: [0.02,0.05,0.08,0.11,0.15,0.20]  # Probability of using the corresponding patch size.
    probs: [0.1,0.2,0.22,0.25,0.27,0.25]  # Probability of using the corresponding patch size.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    # mini_batch_sizes: [8]   
    # iters: [300000]
    # gt_size: 128   
    # gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedMutiImage
    dataroot_gt: '/mnt/mnt/data2/YTH/FLSData/MDWdenoise/sorted/denoise/RestormerSuperResolutionParam2'  # `高质量图像文件夹路径`
    dataroot_lq: '/mnt/mnt/data2/YTH/FLSData/MDWdenoise/sorted/noise1/origin'  # 低   geometric_augs: true
    io_backend:
      type: disk
    num_pairs: 7
    stride_range: [1,10]

# network structures
network_g:
  type: KDLAE_student
  inp_channels: 1
  out_channels: 1
  residual: true
  hidden_channels: [16, 32, 64]


# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~ #/mnt/data1/YTH/project/denoise/SonarDenoise/Restormer/experiments/dev_TimeSonarMinier_stride10_lower_prob_5in_timeposeembed_3/models/net_g_220000.pth

# training settings
train:
  total_iter: 100000
  warmup_iter: 1000 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [40000, 60000]       
    restart_weights: [1,2]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1LossForVideoFrames
    l1loss_weight: 0.9
    temporal_weight: 0.1
    reduction: mean


# validation settings
val:
  window_size: 8
  val_freq: !!float 500e3
  save_img: false
  rgb2bgr: false
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
